In [26]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [27]:
def create_board():
    return np.zeros((3,3), dtype = int)

In [28]:
board = create_board()

In [29]:
print(board)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
def place(board, player, position):
    if((board[position]) == 0):
        board[position] = player
        print(board)
    else:
        print("There is already a marker here.")

In [31]:
place(board, 1, (0,0))

[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [32]:
def possibilities(board):
    ret = []
    for a in range(3):
        for b in range(3):
            if(board[a,b] == 0):
                ret.append((a,b))
                
    return ret

In [33]:
possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [37]:
def random_place(board, player):
    board[random.choice(possibilities(board))] = player
    print(board)

In [35]:
random_place(board, 2)

[[1 0 0]
 [2 0 0]
 [0 0 0]]


In [36]:
random_place(board, 1)

[[1 0 0]
 [2 0 0]
 [1 0 0]]


In [50]:
random.seed(1)
board = create_board()

random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)

[[0 0 1]
 [0 0 0]
 [0 0 0]]
[[0 2 1]
 [0 0 0]
 [0 0 0]]
[[0 2 1]
 [0 1 0]
 [0 0 0]]
[[2 2 1]
 [0 1 0]
 [0 0 0]]
[[2 2 1]
 [0 1 0]
 [0 1 0]]
[[2 2 1]
 [0 1 0]
 [0 1 2]]
[[2 2 1]
 [0 1 1]
 [0 1 2]]
[[2 2 1]
 [0 1 1]
 [2 1 2]]
[[2 2 1]
 [1 1 1]
 [2 1 2]]


In [40]:
def row_win(board, player):
    check = (board == player)
    return (np.all(check[0]) or np.all(check[1]) or np.all(check[2]))
        

In [51]:
row_win(board, 1)

True

In [43]:
def col_win(board, player):
    check = (board == player)
    return (np.all(check[:,0]) or np.all(check[:,1]) or np.all(check[:,2]))

In [52]:
col_win(board, 1)

False

In [45]:
def diag_win(board, player):
    check = (board == player)
    return (np.all(np.array([check[0,0], check[1,1], check[2,2]]))\
           or np.all(np.array([check[2,0], check[1,1], check[2,0]])))

In [53]:
diag_win(board, 2)

False